
```{r}
rnase.zt
ctrl.zt
normalized.zt <- cbind(ctrl.zt,rnase.zt)
```


```{r}
library(ggplot2)

# Anzahl der Zeilen im Dataframe
num_rows <- nrow(normalized.zt)

# Erstelle einen leeren Plot für jeden Graphen
plots_RNase <- list()

# Iteriere über jede Zeile und erstelle den stetigen Graphen
for (i in 1:num_rows) {
  row_data <- normalized.zt[i, ]
  
  # Überprüfe, ob genügend nicht-NA-Werte vorhanden sind
  if (sum(!is.na(row_data)) >= 2) {
    df <- data.frame(x = 1:length(row_data), y = as.numeric(row_data))
    
    # Erstelle den Plot mit ggplot2 
    p <- ggplot(df, aes(x = x, y = y, color = "green")) +
      geom_line() +
      xlab("X-Achse") +
      ylab("Y-Achse")
    
    # Speichere den Plot im List-Objekt
    plots_RNase[[i]] <- p
  } else {
    # Falls nicht genügend nicht-NA-Werte vorhanden sind, füge einen leeren Plot hinzu
    plots_RNase[[i]] <- NULL
  }
}

# Zugriff auf die einzelnen Plots
# Zum Beispiel: plots_RNase[[1]] für den ersten Plot, plots_RNase[[2]] für den zweiten Plot, usw.
```
